macro(SET_COMMON_TARGET_PROPERTIES TRGT HERMES_VERSION)
	set(HERMES_VERSION ${HERMES_VERSION})
  find_package(HERMES REQUIRED)

	target_link_libraries(${TRGT} ${HERMES_LIBRARY})
  target_link_libraries(${TRGT} ${HERMES_COMMON_LIBRARY} ${MATIO_LIBRARY} ${BSON_LIBRARY} ${GLUT_LIBRARY} ${GL_LIBRARY} ${GLEW_LIBRARY} ${PTHREAD_LIBRARY} ${ANTTWEAKBAR_LIBRARY} ${XSD_LIBRARY} ${XERCES_LIBRARY} ${LIBIBERTY_LIBRARY} ${PJLIB_LIBRARY} ${LAPACK_LIBRARY} ${CLAPACK_LIBRARY} ${BLAS_LIBRARY})
  target_link_libraries(  ${TRGT}
      ${EXODUSII_LIBRARIES}
      ${HDF5_LIBRARY}
      ${METIS_LIBRARY}
      ${UMFPACK_LIBRARIES} ${PARALUTION_LIBRARY}
      ${TRILINOS_LIBRARIES}
      ${PETSC_LIBRARIES}
      ${MUMPS_LIBRARIES}
      ${SUPERLU_LIBRARY}
      ${LAPACK_LIBRARIES}
      ${STACK_WALKER_LIBRARY}
      ${PTHREAD_LIBRARY}
      ${TCMALLOC_LIBRARY}
      ${MPI_LIBRARIES}
      ${SCALAPACK_LIBRARIES}
      ${CLAPACK_LIBRARY}
      ${BLAS_LIBRARY}
      ${F2C_LIBRARY}
      ${PJLIB_LIBRARY}
      ${BFD_LIBRARY}
      ${LIBIBERTY_LIBRARY}
      ${BSON_LIBRARY}
      ${MATIO_LIBRARY}
      ${WINBLAS_LIBRARY} 
      ${ADDITIONAL_LIBS}
    )
	
	# Is empty if WITH_TRILINOS = NO
	target_link_libraries(${TRGT} ${TRILINOS_LIBRARIES})
endmacro(SET_COMMON_TARGET_PROPERTIES)
