INCLUDE(FindPackageHandleStandardArgs)

if(${HERMES_VERSION} STREQUAL "HERMES2D")
	FIND_LIBRARY(HERMES_LIBRARY NAMES hermes2d hermes2d-debug PATHS ${HERMES_DIRECTORY} /usr/lib /usr/local/lib)
	FIND_PATH(HERMES_INCLUDE hermes2d.h ${HERMES2D_INCLUDE_PATH} /usr/lib /usr/local/lib)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(HERMES DEFAULT_MSG HERMES_LIBRARY HERMES_INCLUDE)
endif(${HERMES_VERSION} STREQUAL "HERMES2D")
